[workspace]
authors = ["Morten Enemark Lund <melund@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
name = "attractive-typst-resume"
platforms = ["win-64"]
version = "0.1.0"


[dependencies]
ruby = ">=3.4.7,<4"
fontconfig = ">=2.15.0,<3"
